export const SITE = {
  website: "https://cynicowl.github.io", 
  author: "eunsang",
  profile: "https://github.com/CynicOwl",
  desc: "A swimming pool with many waters",
  title: "CynicDog",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,  
  showArchives: true,
  showBackButton: true, 
  editPost: {
    enabled: false,
    text: "Edit",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr", 
  lang: "en", 
  timezone: "Asia/Seoul", 
} as const;
